const {logger,} = require('./util/winston');

const express = require('express');
const router = express.Router();
const ServerStatus = require('./util/server-status');
const ApiToken = require('./api-token');
const {
    LICENSEFILES_PATH,
    DFM_INPUT_HOST,
    ENGINE_TARGETS,
} = require('../config');

const LicenseFile = require('./license/license-file');
const {getWatcher,} = require('./file-watcher');

const stats = new ServerStatus();

function getWatchedPaths() {
    //flatten the arrays of paths to single string
    return Object.values(getWatcher())
        .map(watcher => Object.keys(watcher.getWatched()).pop())
        .join(', ');
}

router.get('/status', (req, res) => {
    logger.verbose('Status request.');
    const watchedPaths = getWatchedPaths();
    const status = stats.getStatus();
    res.send({status, watchedPaths,});
});

/*
 * How long the engine gets to accept a calculation. Nico's interface answers the
 * moment it has queued the run — it does not wait for the calculation — so this
 * only has to cover a handshake, and an engine that has stopped answering used to
 * hold this HTTP request, and the customer's browser, open indefinitely.
 *
 * It has to stay strictly under the site's own client timeout — dfm-core's
 * Api\Client::TIMEOUT, 15s — or the site gives up first and the customer reads a
 * cURL message instead of the 504 below. Measured at 15s the two fired within
 * 50ms of each other and the site lost. 10s leaves the 504 five seconds to arrive.
 */
const ENGINE_TIMEOUT_MS = 10000;

/**
 * Relay a calculation request to the DFM engine.
 *
 * The mapping from the form's field names to the engine's four-letter keys used
 * to live here, in src/params/. It lives in the WordPress plugin now
 * (Api\EngineQuery — see PROTOCOL.md §3 and the port plan's task 49), which is
 * where the fields, their option lists and the whitelist that filters them
 * already were. What arrives is the finished query string plus the *name* of an
 * engine; this resolves the name against ENGINE_TARGETS and passes the query
 * through untouched.
 *
 * The target stays a name on purpose. A URL out of a request body would make this
 * fetch whatever it is told, and the alternative — the plugin building the whole
 * URL — would mean the engine's LAN address in a wp-config on a machine that
 * cannot reach it.
 *
 * @param string preview_id Unique ID to tag images
 * @param string query      Query string for the engine, already mapped
 * @param string engine     Which engine machine to send it to; `main` today
 */
router.post('/preview/:preview_id', ApiToken.middleware, async (req, res) => {
    const {preview_id,} = req.params;
    const {query, engine,} = req.body;
    logger.verbose('Incoming request for preview for %s', preview_id);

    const errorResponse = (message, status = 500) => {
        logger.error(`Error sending params to DFM: ${message}`);
        res.status(status);
        res.send({result: false, preview_id, error: message,});
    };

    //Everything the mapping can emit is a digit, a dot, a minus or an ordinal,
    //so this is not a filter on legitimate input: it is a guard on appending a
    //request body to a URL. A newline or a `#` in here would be somebody else's
    //idea, not the plugin's.
    if (typeof query !== 'string' || !/^[A-Za-z0-9;.\-_=&]+$/.test(query)) {
        return errorResponse('Missing or malformed query', 422);
    }

    const target = ENGINE_TARGETS[engine];
    if (target === undefined) {
        return errorResponse('Unknown engine', 422);
    }
    const url = `${DFM_INPUT_HOST}:${target.port}${target.path}`;

    let response;

    try {
        response = await fetch(`${url}?${query}`, {signal: AbortSignal.timeout(ENGINE_TIMEOUT_MS),});
    } catch (err) {
        const timedOut = err.name === 'TimeoutError' || err.name === 'AbortError';

        return errorResponse(
            timedOut ? `The calculation engine did not answer within ${ENGINE_TIMEOUT_MS / 1000}s` : err.message,
            timedOut ? 504 : 502
        );
    }

    if (!response.ok) {
        return errorResponse((await response.text()).trim().substring(0, 500), response.status);
    }

    //The query is not logged. It carries the customer's licence key, and this
    //line used to write it to disk on every calculation.
    logger.info('Params for %s were sent to %s.', preview_id, url);
    res.send({result: true, preview_id,});
});

/**
 * Send license data to License Application
 * @param object data Data from Digital River
 * @param string key Generated key
 */
router.post('/license', ApiToken.middleware, (req, res) => {
    const {data, key, userId,} = req.body;
    logger.verbose('Incoming registration for license %s', key);
    let result = false;

    //The key becomes a filename directly below. Keys are generated by the site
    //and have always been alphanumeric with dashes, so this rejects nothing real
    //— it closes the same traversal that PreviewZip::ID_PATTERN closes on the
    //other side of the wire.
    if (typeof key !== 'string' || !/^[A-Za-z0-9-]{1,64}$/.test(key)) {
        logger.error('Refused a license registration with a malformed key');
        res.status(422);

        return res.send({result, error: 'Malformed license key',});
    }

    const licenseFile = new LicenseFile(key, data, userId);
    licenseFile.write(LICENSEFILES_PATH).then(result => {
        logger.info('Licensefile for %s saved in %s.', key, LICENSEFILES_PATH);
        res.send({result,});
    }).catch(error => res.send({result, error,}));
});

module.exports = router;